### PR TITLE
Drag between months weeks and days

### PR DESCRIPTION
**Pull request by rmanalan**
caldnd

### CODE REVIEW

**Comment by rmanalan** [comment]
[Add support for moving events (via DnD) from one month to the next](https://trello.com/c/DO5129Pq/87-add-support-for-moving-events-via-dnd-from-one-month-to-the-next)

**Comment by mpcowan** [comment]
The idea is to get this merged in upstream right?

**Comment by rmanalan** [comment]
Eventually

**Comment by rmanalan** [comment]
@mpcowan sorry... I should have added more context with that last comment. I haven't prepared an upstream PR because I am failing to do this cleanly with the current DnD design. The issue is with the `onNavigate` fn. Views implement their own `onNavigate` (which navigates between dates). However, since `withDragAndDrop()` is wrapper component, it can't get access to the view's implementation of `onNavigate` (month, week, etc). The best I've been able to do is get the child context's `onNavigate` prop which is the `onNavigate` supplied when instantiating the calendar (i.e., our `onNavigate`).

Ideally, this should be implemented as a black box. The component user shouldn't have to supply an `onNavigate` for this to work.

One more thing I'd like to try is implementing getContext inside of the views themselves... although that's pretty ugly. Also, React context has been redone in the latest versions using more of a pub/sub model. However, the existing components still use the legacy context functionality.

If you have other ideas, I'm all ears.

**Comment by rmanalan** [comment]
Upstream PR: https://github.com/intljusticemission/react-big-calendar/pull/896

**Comment by rmanalan** [comment]
@mpcowan @dtb I'm gonna merge this in if you don't mind. It's basically the mirror of what I submitted upstream. Just want to close out any remaining work that I had in flight.

**Comment by dtb** [comment]
[Welcome Back](https://trellis.coffee/c/smXm8fFT/3-welcome-back)

**Comment by rmanalan** [comment]
???

**Pull request closed without merging**
